name: huaweimlapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  huawei_ml_text: ^3.2.0+301
  image_picker: ^0.8.5+3
  camera: ^0.10.0
  huawei_ml_language: ^3.2.0+301
  assets_audio_player: ^3.0.5
  file_picker: ^5.0.0
  just_audio: ^0.9.28
  huawei_ml_image: ^3.2.0+301
  image: 3.2.0
  huawei_ar: ^2.13.0+5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

